import React, { createContext, useContext, useState } from 'react';

const strings = {
  en: {
    // Navigation
    home:         'Home',
    myTasks:      'My Tasks',
    wallet:       'Wallet',
    team:         'Team',
    profile:      'Profile',

    // Home
    greeting:     'Hi',
    todayIncome:  "Today's income",
    balance:      'Balance',
    showUSD:      'Show USD',
    showETB:      'Show ETB',
    availableTasks:'Available tasks',
    found:        'found',
    noTasks:      'No tasks in this category',
    noTasksSub:   'Try a different category or check back later',

    // Tasks
    acceptTask:      'Accept task',
    submitReview:    'Submit for review',
    markComplete:    'Mark as completed',
    submitWork:      'Submit your work',
    requirements:    'Requirements',
    progress:        'Progress',
    spotsLeft:       'spots left',
    estTime:         'min',
    workDeposit:     'Work deposit required',
    refundable:      'refundable',
    taskAccepted:    'Task accepted!',
    taskAcceptedSub: 'Complete the task and submit your work to get paid.',
    submitted:       'Submitted!',
    submittedSub:    'Your work is under review. Payment will be credited once approved.',
    completed:       'Completed!',
    required:        'Required',
    describeWork:    'Describe what you completed in detail…',
    completedPaid:   'Completed — paid to your wallet',
    rejected:        'Rejected',
    taskTrailer:     'Task Trailer',
    watchBefore:     'Watch before starting',
    submitHint:      'Be specific — describe exactly what you did to complete this task.',
    charCount:       'chars',
    taskCompleted:   'Task Completed!',
    paidToWallet:    'has been paid to your wallet',
    submissionRejected: 'Submission Rejected',
    editResubmit:    'You can edit your submission and resubmit.',
    earn:            'Earn',

    // My Tasks
    myTasksTitle:  'My Tasks',
    myTasksSub:    'Track and manage your work',
    totalEarned:   'Total earned',
    inProgress:    'In Progress',
    inReview:      'In Review',
    done:          'Done',
    total:         'Total',
    noTasksYet:    'No tasks yet',
    acceptFromHome:'Accept tasks from the Home screen to get started',
    browseTasks:   'Browse tasks',
    tapResubmit:   'Tap to edit and resubmit →',

    // Profile
    personalInfo:    'Personal info',
    fullName:        'Full name',
    emailAddress:    'Email address',
    emailHint:       'Email cannot be changed',
    phoneNumber:     'Phone number',
    referralCode:    'Referral code',
    shareEarn:       'Share to earn commissions',
    saveChanges:     'Save changes',
    changePassword:  'Change password',
    currentPassword: 'Current password',
    newPassword:     'New password',
    confirmPassword: 'Confirm new password',
    updatePassword:  'Update password',
    notifPrefs:      'Notification preferences',
    notifSub:        'Choose what you want to be notified about.',
    savePrefs:       'Save preferences',
    signOut:         'Sign out',
    signOutConfirm:  'Are you sure you want to sign out?',
    cancel:          'Cancel',
    strength:        'Strength',
    weak:            'Weak',
    fair:            'Fair',
    strong:          'Strong',

    // Notifications
    notifications: 'Notifications',
    markAllRead:   'Read all',
    clear:         'Clear',
    clearConfirm:  'This will permanently delete all notifications.',
    clearAll:      'Clear all',
    noNotifs:      'No notifications yet',
    noNotifsSub:   "You're all caught up! Check back later.",
    unread:        'Unread',

    // Notifications (detailed)
    notifTasks:        'Task updates',
    notifTasksSub:     'Assignments, reviews, deadlines',
    notifIncome:       'Income alerts',
    notifIncomeSub:    'Earnings & bonuses',
    notifReferrals:    'Referral events',
    notifReferralsSub: 'New signups & commissions',
    notifWallet:       'Wallet transactions',
    notifWalletSub:    'Deposits, withdrawals',
    notifTeam:         'Team activity',
    notifTeamSub:      'Member progress & team bonuses',
    no:                'No',

    // Wallet
    incomeWallet:  'Income wallet',
    personalWallet:'Personal wallet',
    deposit:       'Deposit',
    withdraw:      'Withdraw',
    transactions:  'Transactions',
    totalEarned2:  'Total earned',
    referralBonus: 'Referral bonus',
    recentTx:      'Recent transactions',
    viewAll:       'View all',
    noTx:          'No transactions yet',
    withdrawRequest:'Request withdrawal',
    amountMin:     'Amount (ETB) — min 200',
    paymentMethod: 'Payment method',
    accountNumber: 'Account / phone number',
    accountName:   'Account name',
    confirmWithdraw:'Confirm withdrawal',
    minWithdraw:   'Minimum withdrawal is 200 ETB',
    accountRequired:'Account details are required',
    withdrawSubmitted:'Withdrawal request submitted. Processing within 24 hours.',
    recharge:      'Recharge',
    exchangeRate:  'Exchange rate: 1 USD =',
    workDepositHeld:'Work deposit held',
    refundedOnCompletion:'refunded on task completion',

    // Income
    perTask:       'Per task',
    tasksPerDay:   'tasks/day',
    recommended:   'Recommended daily',
    teamToday:     'Team today',
    allTimeEarned: 'All-time earned',
    thirtyDays:    '30-day earnings',
    levelProgress: 'Level progress',
    tasksToNextLevel:'more tasks to advance to the next level',
    readyToAdvance:'🎉 Ready to advance to next level!',
    todaySummary:  "Today's summary",
    tasksDone:     'Tasks done',
    dailyLimit:    'Daily limit',
    walletBreakdown:'Wallet breakdown',
    levelPerks:    'Your level perks',
    referralCommission:'Referral commission',
    tapBarDetails: 'Tap a bar for details',

    // Handbook
    guide:          'Guide',
    levelRules:     'Level rules',
    depositRequired:'Deposit required',
    dailyMax:       'Daily maximum',
    referralBonusLabel:'Referral bonus',
    teamBonus:      'Team bonus',
    tasksToAdvance: 'Tasks to advance',
    handbookInfo:   'Higher levels unlock more tasks per day and better rewards. Tap any level to see full details.',
    perTaskEarning: 'Per task earning',

    // Auth
    signIn:      'Sign in',
    signUp:      'Sign up',
    email:       'Email address',
    password:    'Password',
    forgotPw:    'Forgot password?',
    noAccount:   "Don't have an account?",
    createFree:  'Create one free →',
    tagline:     'Earn money completing real tasks 🇪🇹',
    welcomeBack: 'Welcome back 👋',
    signInToContinue:'Sign in to continue earning',
    workers:     'Workers',
    tasks2:      'Tasks',
    paidOnTime:  'Paid on time',
    agreeTerms:  'By signing in you agree to our Terms & Privacy Policy',

    // Register
    createAccount: 'Create account',
    joinTagline:   'Join thousands earning with ስራ-Sira',
    name:          'Full name',
    namePlaceholder:'Your full name',
    referralOptional:'Referral code (optional)',
    alreadyAccount:  'Already have an account?',
    signInLink:      'Sign in →',
    registerSuccess: 'Welcome!',
    registerSuccessSub:'Your account has been created.',

    // Team
    yourNetwork:    'Your network overview',
    teamIncomeToday:'Team income today',
    fromMembers:    'From {n} members',
    totalMembers:   'Total',
    active7d:       'Active (7d)',
    direct:         'Direct',
    tierA:          'Tier A',
    tierB:          'Tier B',
    tierC:          'Tier C',
    teamTree:       '🌳 Team tree',
    leaderboard:    '🏆 Leaderboard',
    tierADirect:    'Tier A — Direct',
    tierBLevel2:    'Tier B — Level 2',
    tierCLevel3:    'Tier C — Level 3',
    noTeamYet:      'No team members yet',
    noTeamYetSub:   'Share your referral code to grow your team',
    inviteFriends:  'Invite friends',
    noLeaderboard:  'No leaderboard data yet',
    referrals:      'referrals',
    tasks:          'tasks',

    // Deposit
    depositFunds:   'Deposit funds',
    chooseAmount:   'Choose amount',
    customAmount:   'Custom amount',
    enterAmount:    'Enter amount in ETB',
    chooseMethod:   'Payment method',
    depositInfo:    'Send payment to the number below, then enter your transaction reference.',
    sendTo:         'Send to',
    txReference:    'Transaction reference',
    txRefPlaceholder:'Enter CBE/Telebirr reference',
    submitDeposit:  'Submit deposit request',
    depositSubmitted:'Deposit request submitted! We will verify and credit your account within 24 hours.',
    minDeposit:     'Minimum deposit is 100 ETB',
    refRequired:    'Transaction reference is required',

    // Notifications Screen
    unreadMessages: 'unread message',
    unreadMessages2:'unread messages',
    allCaughtUp:    "You're all caught up! Check back later.",

    // General
    loading:  'Loading…',
    error:    'Error',
    success:  'Success',
    save:     'Save',
    back:     'Back',
    tryAgain: 'Try a different filter',
    deposit:  'Deposit',
  },

  am: {
    // Navigation
    home:         'ዋና ገጽ',
    myTasks:      'ተግባሮቼ',
    wallet:       'ቦርሳ',
    team:         'ቡድን',
    profile:      'መገለጫ',

    // Home
    greeting:     'ሰላም',
    todayIncome:  'የዛሬ ገቢ',
    balance:      'ቀሪ ሂሳብ',
    showUSD:      'USD አሳይ',
    showETB:      'ETB አሳይ',
    availableTasks:'ያሉ ተግባሮች',
    found:        'ተገኝቷል',
    noTasks:      'በዚህ ምድብ ተግባሮች የሉም',
    noTasksSub:   'ሌላ ምድብ ይሞክሩ ወይም ቆይተው ይመልከቱ',

    // Tasks
    acceptTask:      'ተግባር ተቀበል',
    submitReview:    'ለግምገማ አስገባ',
    markComplete:    'እንደተጠናቀቀ ምልክት አድርግ',
    submitWork:      'ስራዎን ያስገቡ',
    requirements:    'መስፈርቶች',
    progress:        'እድገት',
    spotsLeft:       'ቦታዎች ቀርተዋል',
    estTime:         'ደቂቃ',
    workDeposit:     'የስራ ተቀማጭ ያስፈልጋል',
    refundable:      'የሚመለስ',
    taskAccepted:    'ተግባር ተቀብሏል!',
    taskAcceptedSub: 'ተግባሩን ጨርሰው ስራዎን ያስገቡ።',
    submitted:       'ተልኳል!',
    submittedSub:    'ስራዎ በግምገማ ላይ ነው። ክፍያ ሲፈቀድ ይገባል።',
    completed:       'ተጠናቅቋል!',
    required:        'ያስፈልጋል',
    describeWork:    'ያጠናቀቁትን በዝርዝር ይግለጹ…',
    completedPaid:   'ተጠናቅቋል — ወደ ቦርሳዎ ተከፍሏል',
    rejected:        'ተቀባይነት አላገኘም',
    taskTrailer:     'የተግባር ትሬለር',
    watchBefore:     'ከመጀመርዎ በፊት ይመልከቱ',
    submitHint:      'ትክክለኛ ይሁኑ — ተግባሩን ለማጠናቀቅ ያደረጉትን ይግለጹ።',
    charCount:       'ቁምፊዎች',
    taskCompleted:   'ተግባር ተጠናቋል!',
    paidToWallet:    'ወደ ቦርሳዎ ተከፍሏል',
    submissionRejected: 'ማስገቢያ ተቀባይነት አላገኘም',
    editResubmit:    'ማስገቢያዎን ማስተካከል እና እንደገና ማስገባት ይችላሉ።',
    earn:            'ያግኙ',

    // My Tasks
    myTasksTitle:  'ተግባሮቼ',
    myTasksSub:    'ስራዎን ይከታተሉ እና ያስተዳድሩ',
    totalEarned:   'ጠቅላላ ያገኙት',
    inProgress:    'በሂደት ላይ',
    inReview:      'በግምገማ ላይ',
    done:          'ተጠናቅቋል',
    total:         'ጠቅላላ',
    noTasksYet:    'እስካሁን ተግባሮች የሉም',
    acceptFromHome:'ከዋና ገጽ ተግባሮችን ይቀበሉ',
    browseTasks:   'ተግባሮችን ይዳስሱ',
    tapResubmit:   'ለማስተካከል እና እንደገና ለማስገባት ይጫኑ →',

    // Profile
    personalInfo:    'የግል መረጃ',
    fullName:        'ሙሉ ስም',
    emailAddress:    'ኢሜይል አድራሻ',
    emailHint:       'ኢሜይል ሊቀየር አይችልም',
    phoneNumber:     'ስልክ ቁጥር',
    referralCode:    'የሪፈራል ኮድ',
    shareEarn:       'አጋሩ እና ኮሚሽን ያግኙ',
    saveChanges:     'ለውጦችን አስቀምጥ',
    changePassword:  'ፓስወርድ ቀይር',
    currentPassword: 'አሁን ያለው ፓስወርድ',
    newPassword:     'አዲስ ፓስወርድ',
    confirmPassword: 'አዲስ ፓስወርድ አረጋግጥ',
    updatePassword:  'ፓስወርድ አዘምን',
    notifPrefs:      'የማሳወቂያ ምርጫዎች',
    notifSub:        'ምን ማሳወቂያ እንደሚፈልጉ ይምረጡ።',
    savePrefs:       'ምርጫዎችን አስቀምጥ',
    signOut:         'ውጣ',
    signOutConfirm:  'እርግጠኛ ነዎት መውጣት ይፈልጋሉ?',
    cancel:          'ሰርዝ',
    strength:        'ጥንካሬ',
    weak:            'ደካማ',
    fair:            'መካከለኛ',
    strong:          'ጠንካራ',

    // Notifications
    notifications: 'ማሳወቂያዎች',
    markAllRead:   'ሁሉንም አንብብ',
    clear:         'አጽዳ',
    clearConfirm:  'ሁሉም ማሳወቂያዎች በቋሚነት ይሰረዛሉ።',
    clearAll:      'ሁሉንም አጽዳ',
    noNotifs:      'እስካሁን ማሳወቂያዎች የሉም',
    noNotifsSub:   'ሁሉም ወቅታዊ ነው! ቆይተው ይመልከቱ።',
    unread:        'ያልተነበበ',

    // Notifications (detailed)
    notifTasks:        'የተግባር ዝማኔዎች',
    notifTasksSub:     'ምደባዎች፣ ግምገማዎች፣ ቀነ-ገደቦች',
    notifIncome:       'የገቢ ማሳወቂያዎች',
    notifIncomeSub:    'ገቢዎች እና ጉርሻዎች',
    notifReferrals:    'የሪፈራል ክስተቶች',
    notifReferralsSub: 'አዲስ ምዝገባዎች እና ኮሚሽኖች',
    notifWallet:       'የቦርሳ ግብይቶች',
    notifWalletSub:    'ተቀማጭ፣ ማስወጣት',
    notifTeam:         'የቡድን እንቅስቃሴ',
    notifTeamSub:      'የአባል እድገት እና ጉርሻዎች',
    no:                'የሌለ',

    // Wallet
    incomeWallet:   'የገቢ ቦርሳ',
    personalWallet: 'የግል ቦርሳ',
    deposit:        'ተቀማጭ',
    withdraw:       'አውጣ',
    transactions:   'ግብይቶች',
    totalEarned2:   'ጠቅላላ ያገኙት',
    referralBonus:  'የሪፈራል ጉርሻ',
    recentTx:       'የቅርብ ጊዜ ግብይቶች',
    viewAll:        'ሁሉንም ይመልከቱ',
    noTx:           'እስካሁን ግብይቶች የሉም',
    withdrawRequest:'የማስወጣት ጥያቄ',
    amountMin:      'መጠን (ETB) — ቢያንስ 200',
    paymentMethod:  'የክፍያ ዘዴ',
    accountNumber:  'የሂሳብ / ስልክ ቁጥር',
    accountName:    'የሂሳብ ስም',
    confirmWithdraw:'ማስወጣት አረጋግጥ',
    minWithdraw:    'ዝቅተኛ ማስወጣት 200 ETB ነው',
    accountRequired:'የሂሳብ መረጃ ያስፈልጋል',
    withdrawSubmitted:'የማስወጣት ጥያቄ ቀርቧል። በ24 ሰዓት ውስጥ ይሰራል።',
    recharge:       'ሪቻርጅ',
    exchangeRate:   'የምንዛሬ ተመን: 1 USD =',
    workDepositHeld:'የስራ ተቀማጭ',
    refundedOnCompletion:'ተግባሩ ሲጠናቀቅ ይመለሳል',

    // Income
    perTask:        'በተግባር',
    tasksPerDay:    'ተግባሮች/ቀን',
    recommended:    'የሚመከር ዕለታዊ',
    teamToday:      'ቡድን ዛሬ',
    allTimeEarned:  'ጠቅላላ ያገኙት',
    thirtyDays:     'የ30 ቀን ገቢ',
    levelProgress:  'የደረጃ እድገት',
    tasksToNextLevel:'ተጨማሪ ተግባሮች ወደ ቀጣዩ ደረጃ ለማደግ',
    readyToAdvance: '🎉 ወደ ቀጣዩ ደረጃ ለመሄድ ዝግጁ ነዎት!',
    todaySummary:   'የዛሬ ማጠቃለያ',
    tasksDone:      'ተጠናቀቁ ተግባሮች',
    dailyLimit:     'ዕለታዊ ገደብ',
    walletBreakdown:'የቦርሳ ዝርዝር',
    levelPerks:     'የደረጃ ጥቅሞችዎ',
    referralCommission:'የሪፈራል ኮሚሽን',
    tapBarDetails:  'ዝርዝር ለማየት አሞሌ ይጫኑ',

    // Handbook
    guide:           'መመሪያ',
    levelRules:      'የደረጃ ደንቦች',
    depositRequired: 'የሚፈለግ ተቀማጭ',
    dailyMax:        'ዕለታዊ ከፍተኛ',
    referralBonusLabel:'የሪፈራል ጉርሻ',
    teamBonus:       'የቡድን ጉርሻ',
    tasksToAdvance:  'ለማደግ ተግባሮች',
    handbookInfo:    'ከፍተኛ ደረጃዎች በቀን ብዙ ተግባሮች እና የተሻሉ ሽልማቶችን ይሰጣሉ። ሙሉ ዝርዝር ለማየት ደረጃ ይጫኑ።',
    perTaskEarning:  'በተግባር ያለ ገቢ',

    // Auth
    signIn:       'ግባ',
    signUp:       'ተመዝገብ',
    email:        'ኢሜይል አድራሻ',
    password:     'ፓስወርድ',
    forgotPw:     'ፓስወርድ ረሱ?',
    noAccount:    'መለያ የለዎትም?',
    createFree:   'በነጻ ይፍጠሩ →',
    tagline:      'እውነተኛ ተግባሮችን በማጠናቀቅ ገንዘብ ያግኙ 🇪🇹',
    welcomeBack:  'እንኳን ደህና መጡ 👋',
    signInToContinue:'ለመቀጠል ይግቡ',
    workers:      'ሰራተኞች',
    tasks2:       'ተግባሮች',
    paidOnTime:   'በጊዜ ተከፍሏል',
    agreeTerms:   'በመግባትዎ የኛን ውሎች እና የግላዊነት መመሪያ ይስማማሉ',

    // Register
    createAccount:   'መለያ ፍጠር',
    joinTagline:     'ከሺዎች ጋር ይቀላቀሉ ስራ-Sira ላይ',
    name:            'ሙሉ ስም',
    namePlaceholder: 'ሙሉ ስምዎን ያስገቡ',
    referralOptional:'የሪፈራል ኮድ (አማራጭ)',
    alreadyAccount:  'መለያ አለዎት?',
    signInLink:      'ግባ →',
    registerSuccess: 'እንኳን ደህና መጡ!',
    registerSuccessSub:'መለያዎ ተፈጥሯል።',

    // Team
    yourNetwork:    'የእርስዎ ኔትወርክ አጠቃላይ ዕይታ',
    teamIncomeToday:'የቡድን ገቢ ዛሬ',
    fromMembers:    'ከ{n} አባላት',
    totalMembers:   'ጠቅላላ',
    active7d:       'ንቁ (7 ቀን)',
    direct:         'ቀጥታ',
    tierA:          'ደረጃ A',
    tierB:          'ደረጃ B',
    tierC:          'ደረጃ C',
    teamTree:       '🌳 የቡድን ዛፍ',
    leaderboard:    '🏆 ደረጃ ሰሌዳ',
    tierADirect:    'ደረጃ A — ቀጥታ',
    tierBLevel2:    'ደረጃ B — ደረጃ 2',
    tierCLevel3:    'ደረጃ C — ደረጃ 3',
    noTeamYet:      'እስካሁን የቡድን አባላት የሉም',
    noTeamYetSub:   'ቡድንዎን ለማሳደግ የሪፈራል ኮድዎን ያጋሩ',
    inviteFriends:  'ጓደኞችን ይጋብዙ',
    noLeaderboard:  'እስካሁን የደረጃ ሰሌዳ መረጃ የለም',
    referrals:      'ሪፈራሎች',
    tasks:          'ተግባሮች',

    // Deposit
    depositFunds:    'ገንዘብ ያስቀምጡ',
    chooseAmount:    'መጠን ይምረጡ',
    customAmount:    'ብጁ መጠን',
    enterAmount:     'በ ETB መጠን ያስገቡ',
    chooseMethod:    'የክፍያ ዘዴ',
    depositInfo:     'ክፍያ ወደ ታቹ ቁጥር ይላኩ፣ ከዚያ የግብይት ማጣቀሻዎን ያስገቡ።',
    sendTo:          'ወደዚህ ይላኩ',
    txReference:     'የግብይት ማጣቀሻ',
    txRefPlaceholder:'የ CBE/Telebirr ማጣቀሻ ያስገቡ',
    submitDeposit:   'የተቀማጭ ጥያቄ ያስገቡ',
    depositSubmitted:'የተቀማጭ ጥያቄ ቀርቧል! በ24 ሰዓት ውስጥ እናረጋግጣለን።',
    minDeposit:      'ዝቅተኛ ተቀማጭ 100 ETB ነው',
    refRequired:     'የግብይት ማጣቀሻ ያስፈልጋል',

    // Notifications Screen
    unreadMessages:  'ያልተነበበ መልዕክት',
    unreadMessages2: 'ያልተነበቡ መልዕክቶች',
    allCaughtUp:     'ሁሉም ወቅታዊ ነው! ቆይተው ይመልከቱ።',

    // General
    loading:  'እየጫነ ነው…',
    error:    'ስህተት',
    success:  'ተሳክቷል',
    save:     'አስቀምጥ',
    back:     'ተመለስ',
    tryAgain: 'ሌላ ማጣሪያ ይሞክሩ',
    deposit:  'ተቀማጭ',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const toggle = () => setLanguage(l => l === 'en' ? 'am' : 'en');
  const t = (key) => strings[language][key] || strings['en'][key] || key;

  return (
    <LanguageContext.Provider value={{ language, toggle, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);